# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get -yqq update
apt-get -yqq remove docker docker-engine docker.io containerd runc
apt-get -yqq install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-get -yqq update
apt-get -yqq install docker-ce docker-ce-cli containerd.io -y
# Restart docker to make sure we get the latest version of the daemon if there is an upgrade
service docker restart
# Make sure we can actually use docker as the vagrant user
usermod -aG docker vagrant
docker --version

# Install docker-compose
echo "Installing docker-compose..."
curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Install development tools
echo "Installing development tools..."
apt-get -yqq install -y make pkg-config librdkafka-dev ntpdate

# Install golang
echo "Installing Go..."
VERSION=1.12.7
OS=linux
ARCH=amd64
curl -fsSL https://dl.google.com/go/go${VERSION}.${OS}-${ARCH}.tar.gz | sudo tar -C /usr/local -xzf -

# Install node?
apt-get install -yqq nodejs npm
npm install npm@latest -g

# Copy SSH keys
cp /vagrant/bashrc /home/vagrant/.bashrc
cp /vagrant/ssh/id_rsa* /home/vagrant/.ssh/
cp /vagrant/ssh/config /home/vagrant/.ssh/

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "ckzed-vm"
  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "ckzed-buster"
  end
  # config.vm.define :buster

  config.vm.provision "ansible" do |an|
    an.playbook = "vagrant.yml"
  end

  # Increase disk size
  config.disksize.size = '64GB'

  # Networking
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)",
                    :mac => "5CA1AB1E0002", use_dhcp_assigned_default_route: true
  # SSH
  config.ssh.forward_agent = true # So that boxes don't have to setup key-less ssh
  # config.ssh.insert_key = false   # To generate a new ssh key and don't use the default Vagrant one

  # Mount directories that we need in the VM
  config.vm.synced_folder "/Users/chirag/Work", "/home/vagrant/Work"
  config.vm.synced_folder "/Users/chirag/Research", "/home/vagrant/Research"
  config.vm.synced_folder "/Users/chirag/.config", "/home/vagrant/.config"
  config.vm.synced_folder "/Users/chirag/.vagrant", "/home/vagrant/.vagrant"

  # Provisioning script
  # config.vm.provision "shell", inline: $script
  config.vm.provision "shell", inline: "apt-get -qqy install apt-transport-https"
  config.vm.provision "shell", path: "provision-as-root.sh"

end
