# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.hostname = "ckzed-vm"

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "ckzed-buster"
  end
  config.vm.define :buster
  # Increase disk size
  config.disksize.size = '64GB'

  config.vm.provision "ansible" do |an|
    an.playbook = "vagrant.yml"
  end

  # Networking
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)",
                    :mac => "5CA1AB1E0002", use_dhcp_assigned_default_route: true
  # SSH
  config.ssh.forward_agent = true # So that boxes don't have to setup key-less ssh
  # config.ssh.insert_key = false   # To generate a new ssh key and don't use the default Vagrant one

  # Mount directories that we need in the VM
  config.vm.synced_folder "/Users/chirag/Work", "/home/vagrant/Work"
  config.vm.synced_folder "/Users/chirag/Research", "/home/vagrant/Research"
  config.vm.synced_folder "/Users/chirag/.config", "/home/vagrant/.config"
  config.vm.synced_folder "/Users/chirag/.vagrant", "/home/vagrant/.vagrant"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # Provisioning script
  config.vm.provision "shell", inline: "apt-get -qqy install apt-transport-https"
  config.vm.provision "shell", path: "/Users/chirag/Research/dvm/debian/provision-as-root.sh"
end
