# ~/.zshrc
#
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
export ZSH="$HOME/.oh-my-zsh"
#export ZSH_THEME="robbyrussell"
export ZSH_THEME="ckzed"
export DISABLE_UPDATE_PROMPT="true"
export CASE_SENSITIVE="true"
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export GOPATH="$HOME/.go"
export PYPATH="$HOME/.local/bin"
export PATH=$PATH:${GOPATH}/bin:${PYPATH}:/usr/local/sbin:
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export HIST_STAMPS="yyyy-mm-dd"
export HISTIGNORE=cd:bg:fg
export HISTSIZE=50000
export SAVEHIST=50000
export HISTFILE="/vagrant/history"
export LANG=en_US.UTF-8

alias adate='TZ=America/Los_Angeles date'
alias ls='ls -FG'
alias cdup='cd $(git rev-parse --show-toplevel)'

plugins=(git python go)
source $ZSH/oh-my-zsh.sh

bindkey '^r' history-incremental-search-backward
source .oh-my-zsh/plugins/history-substring-search/history-substring-search.zsh
zstyle :plugin:history-search-multi-word reset-prompt-protect 1
zstyle ":history-search-multi-word" page-size "8" # Number of entries to show (default is $LINES/3)
zstyle ":history-search-multi-word" highlight-color "fg=yellow,bold" # Color in which to highlight matched, searched text (default bg=17 on 256-color terminals)
zstyle ":plugin:history-search-multi-word" synhl "yes" # Whether to perform syntax highlighting (default true)
zstyle ":plugin:history-search-multi-word" active "underline" # Effect on active history entry. Try: standout, bold, bg=blue (default underline)
zstyle ":plugin:history-search-multi-word" check-paths "yes" # Whether to check paths for existence and mark with magenta (default true)
zstyle ":plugin:history-search-multi-word" clear-on-cancel "yes" # Whether pressing Ctrl-C or ESC should clear entered query
